program: sweeps/texture-transfer/main.py
project: semantic-texture-transfer
entity: vit-vis
method: grid
parameters:
  seed:
    values: [-1]

  dataroot:
    values: ['./datasets/horse_zebra']
  direction:
    values: ['AtoB']  # AtoB or BtoA

  local_A_crops_n_crops:
    values: [1,5]
  local_A_crops_max_cover:
    values: [0.3,0.5]
  local_B_crops_n_crops:
    values: [1]
  local_B_crops_max_cover:
    values: [0.5]
  global_A_crops_n_crops:
    values: [1]
  global_A_crops_min_cover:
    values: [0.95]
  global_B_crops_n_crops:
    values: [1]
  global_B_crops_min_cover:
    values: [0.5,0.95]

  init_type:
    values: ['xavier']  # ['normal', 'xavier', 'kaiming', 'orthogonal']
  init_gain:
    values: [0.02]  # scaling factor for normal, xavier and orthogonal

  lambda_global_cls:
    values: [10.0]
  lambda_local_cls:
    values: [0.0]
  lambda_global_ssim:
    values: [0.0,1.0]
  lambda_local_ssim:
    values: [1.0,4.0]
  lambda_local_identity:
    values: [0.0]
  lambda_global_identity:
    values: [0.0,1.0]
  lambda_entire_ssim:
    values: [0.0]

  dino_model_name:
    values: ['dino_vitb8']
  dino_global_patch_size:
    values: [224]
  dino_local_patch_size:
    values: [96]

  cls_warmup:
    values: [1]
  n_epochs:
    values: [1200]
  scheduler_policy:
    values: ['step']  # [linear | step | plateau | cosine]
  scheduler_n_epochs_decay:
    values: [8]
  scheduler_lr_decay_iters:
    values: [600]

  optimizer:
    values: ['adam']
  optimizer_beta1:
    values: [0.0]
  optimizer_beta2:
    values: [0.99]
  lr:
    values: [0.002]

  log_images_freq:
    values: [10]

metric:
  name: loss

